# Default values for acmefitness.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

service:
  type: ClusterIP
  port: 80

passwords:
  cartRedis: ""
  orderMongodb: ""
  usersMongodb: ""
  catalogMongodb: ""

ingress:
  enabled: false
  certManager: false
  hosts:
    - name: domain.example.com
      tls: true
      tlsSecret: domain-example-com-tls

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
