apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
spec:
  hosts:
  - frontend
  http:
  - fault:
      abort:
        percentage:
          value: 0.5
        httpStatus: 400
    route:
    - destination:
        host: frontend
