apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: catalog
spec:
  hosts:
  - catalog
  http:
  - fault:
      abort:
        percentage:
          value: 1
        httpStatus: 400
    route:
    - destination:
        host: catalog
        version: v1
