apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: catalog
spec:
  hosts:
  - catalog
  http:
    - route:
      - destination:
          host: catalog
          subset: v1
      retries:
        attempts: 2
        perTryTimeout: 2s
      
