apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: catalog
spec:
  hosts:
  - catalog
  http:
  - fault:
      abort:
        httpStatus: 400
        percent: 50
    route:
    - destination:
        host: catalog
        subset: v1
    retries:
      attempts: 3
      perTryTimeout: 2s



