apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: acme-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: acme
spec:
  hosts:
  - "*"
  gateways:
  - acme-gateway
  http:
  - match:
    - headers:
        cookie:
          regex: "logged_in"
    route:
    - destination:
        host: frontend
        subset: v2
        port:
          number: 3000 
  - route:
    - destination:
        host: frontend
        subset: v1
        port:
          number: 3000 